### ISSUE TITLE
Hi, I have some question regarding the datasets

### ISSUE THREAD

**Issue by neolunar7** [CarlSouthall/ADTLib#9]
I have started automatic drum transciption, but I'm lacking the datasets.
I'd like to ask where I can obtain the datasets for training.
Thanks a lot.

**Comment by enini** [comment]
Sorry to bother, but I have one question. After I installed ADTLib successfully, I couldn't use it. It appears that the ADT command line can't be identified. Do you know any solutions?
Thank you very much.

**Comment by enini** [comment]
Me as well lacking training data, did you find datasets for training?
Thank you very much.

**Comment by dai-pei** [comment]
> I have started automatic drum transciption, but I'm lacking the datasets.
> I'd like to ask where I can obtain the datasets for training.
> Thanks a lot.

Me as well lacking training data, did you find datasets for training?
Thank you very much.

**Comment by neolunar7** [comment]
Sorry, I couldn't get one.

**Comment by richard-vogl** [comment]
Hi,
since I have been working on drum transcription for some time, here some links for datasets:

ENST drums: https://perso.telecom-paristech.fr/grichard/ENST-drums/
IDMT-SMT: https://www.idmt.fraunhofer.de/en/business_units/m2d/smt/drums.html
MDB-drums (co-authored by Carl): https://github.com/CarlSouthall/MDBDrums
RBMA13-drums (co-authored by me): http://ifs.tuwien.ac.at/~vogl/datasets/
MIDI-drums (co-authored by me): http://ifs.tuwien.ac.at/~vogl/dafx2018/

Also, if you read related work papers you will find more information to these datasets and links:
https://arxiv.org/pdf/1806.06676
https://archives.ismir.net/ismir2017/paper/000123.pdf
https://archives.ismir.net/ismir2016/paper/000269.pdf
https://archives.ismir.net/ismir2017/paper/000146.pdf
http://m.mr-pc.org/ismir16/website/articles/217_Paper.pdf
https://ieeexplore.ieee.org/document/8350302?reload=true
http://www.musicinformatics.gatech.edu/wp-content_nondefault/uploads/2015/09/Wu_Lerch_2015_Drum%20Transcription%20using%20Partially%20Fixed%20Non-Negative%20Matrix%20Factorization.pdf

Best
Richard

**Comment by dai-pei** [comment]
> Hi,
> since I have been working on drum transcription for some time, here some links for datasets:
> 
> ENST drums: https://perso.telecom-paristech.fr/grichard/ENST-drums/
> IDMT-SMT: https://www.idmt.fraunhofer.de/en/business_units/m2d/smt/drums.html
> MDB-drums (co-authored by Carl): https://github.com/CarlSouthall/MDBDrums
> RBMA13-drums (co-authored by me): http://ifs.tuwien.ac.at/~vogl/datasets/
> MIDI-drums (co-authored by me): http://ifs.tuwien.ac.at/~vogl/dafx2018/
> 
> Also, if you read related work papers you will find more information to these datasets and links:
> https://arxiv.org/pdf/1806.06676
> https://archives.ismir.net/ismir2017/paper/000123.pdf
> https://archives.ismir.net/ismir2016/paper/000269.pdf
> https://archives.ismir.net/ismir2017/paper/000146.pdf
> http://m.mr-pc.org/ismir16/website/articles/217_Paper.pdf
> https://ieeexplore.ieee.org/document/8350302?reload=true
> http://www.musicinformatics.gatech.edu/wp-content_nondefault/uploads/2015/09/Wu_Lerch_2015_Drum%20Transcription%20using%20Partially%20Fixed%20Non-Negative%20Matrix%20Factorization.pdf
> 
> Best
> Richard

Thanks a lot!

**Comment by neolunar7** [comment]
Thanks a lot Richard !
